[package]
name = "conquer-once"
description = "synchronization primitives for lazy and one-time initialization"
version = "0.1.0"
authors = ["Oliver Giersch"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/oliver-giersch/conquer-once.git"
documentation = "https://docs.rs/conquer-once"
keywords = ["lazy", "once", "synchronization", "initialization"]
edition = "2018"
exclude = [".travis.yml", "TODO.md"]

[features]
default = ["std"]
std = []

[dependencies.conquer-util]
version = "0.1.0"
no-default-features = true
features = ["back-off"]
