name: Rust

on:
  push:
    branches: [ master ]
    tags: [ v0.* ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.36.0
          components: clippy
      - run: cargo clippy --all-features
  
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [1.36.0, 1.49.0, stable, nightly]
    steps:
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.os }}
      - run: cargo test --verbose
      - run: cargo test --verbose --no-default-features

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: miri
      - run: cargo miri test