name: Rust

on:
  push:
    branches: [ master ]
    tags: [ v0.* ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.36.0
        with:
          components: clippy
      - run: cargo clippy
      - run: cargo clippy --no-default-features
  
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # test against MSRV and next-MSRV
        rust: [1.36.0, 1.49.0, stable, nightly]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --verbose
      - run: cargo test --verbose --no-default-features

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@miri
      - run: cargo miri test
        env:
          #MIRIFLAGS: -Zmiri-strict-provenance
          MIRIFLAGS: -Zmiri-permissive-provenance